[project]
name = "ai-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.2,<3.0"
]
[tool.uv.pip]
index-url = "http://mirrors.aliyun.com/pypi/simple/"
